### ISSUE TITLE
Misssing Item Photo id=10

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Frontend#12]
<details>
<summary>Missing</summary>

 - The photo of the item, id=10

</details>

<details>
<summary>Actions</summary>

- Repopulate the imageDB for the missing fields.

</details>

**Comment by DenizcanOzpinar** [comment]
![10](https://user-images.githubusercontent.com/55896265/70375754-dd3ba200-1912-11ea-90c9-920b8ba219d8.jpg)
Here it is

**Comment by keremgure** [comment]
> ![10](https://user-images.githubusercontent.com/55896265/70375754-dd3ba200-1912-11ea-90c9-920b8ba219d8.jpg)
> Here it is

@DenizcanOzpinar Thanks! 🙏
