### ISSUE TITLE
shoppingCart page auth middleware missing

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Frontend#28]
@zinedburak , The shoppingCart page implementations #23 and #20 do not include the restriction for user login. Thus, the page crashes when tried to access without logging in.

Possible Fix:

- add the `auth` middleware to shoppingCart.

**Comment by keremgure** [comment]
@zinedburak , Have we made any progress on this? Can you give us an update? Thanks!

**Comment by zinedburak** [comment]
Done
