### ISSUE TITLE
Cannot open new account due to username is too long error you can see the error in detail in comment

### ISSUE THREAD

**Issue by zinedburak** [BuildPC/Frontend#30]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'username' at row 1 (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (deniz, bdeniz@hotmail.com, $2y$10$VPHinudK56Qemk48yFOWiumkRy3OTGKkrnazfbr5sXPK1w1hFPpXC, 2019-12-16 06:33:09, 2019-12-16 06:33:09))

user name referred to here is the e-mail

**Comment by keremgure** [comment]
Can you provide the steps you took that ended up with this error?

**Comment by zinedburak** [comment]
Done
