### ISSUE TITLE
Need new post routes or WebAPI like calls for basket updates

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Frontend#33]
The functionality of the buttons present on the website needs to be implemented.
The prime focus is the buttons that update the basket.
Currently, I can think of two ways of doing this:
 1. An HTTP POST request to a route with necessary data to run the queries.
 2. A WebHook/WebAPI like calls handler to send requests to the backend and run the query. 

***If you have any questions on how to implement this or any suggestions to improve on the ideas or if you have a totally different idea... (you get the idea), please post a comment down below!***

**Comment by zinedburak** [comment]
It is done
