### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mreay** [BuildPC/Frontend#45]
Footer covers some part of the order summary

**Comment by mreay** [comment]
footer still blocks the some sections of the order summary @keremgure @barisozbas @zinedburak

**Comment by barisozbas** [comment]
#58 Try pulling the repo again. It seems like it is fixed if not, define the issue more detailed.

**Comment by mreay** [comment]
pulled the repo and still there is some blocking order summary after filling the basket. Only the first two elements can be seen clearly. after those, tax and total amount cant be seen properly


![resim](https://user-images.githubusercontent.com/18218347/71323392-8ec9fe00-24e3-11ea-81db-2214be8711c6.png)

**Comment by mreay** [comment]
Fixed the problem somehow.
