### ISSUE TITLE
Possible exposure of DB info.

### ISSUE THREAD

**Issue by keremgure** [BuildPC/Frontend#6]
The PR that was merged #4 to the master exposes the DB info since DB parameters were not set at `.env` rather, they are hardcoded.

***Fix before deployment!***
*see line **70***
https://github.com/BuildPC/Frontend/blob/7cea788057b8cc672c61fccbab769ea6082535a1/config/database.php#L65-L72

**Comment by barisozbas** [comment]
I started working on it. ✋

**Comment by keremgure** [comment]
@barisozbas and @zinedburak , Where are we on this? Have you fixed it? I have not seen any pull requests regarding this.

**Comment by zinedburak** [comment]
Done
